### ISSUE TITLE
Submitting to Umbrel

### ISSUE THREAD

**Issue by jimbrend** [getAlby/umbrel-community-app-store#1]
hey @kiwiidb were you still having any issue finishing this?  Do you want to describe what else needs to get done or any problem you're having?

Maybe @nmfretz can help too!

**Comment by MoritzKa** [comment]
@JimSB do you want to help us submitting the app to the Umbrel app store? I guess the app itself is pretty much ready.

**Comment by JimSB** [comment]
Letting @nmfretz know!

**Comment by nmfretz** [comment]
Thanks for pinging me, @JimSB.

@MoritzKa I'm excited to see this on Umbrel! I took a brief look through this repo and here are the steps I would take.
 
1) **Docker Image**:
For the `nostr-wallet-connect` Docker image, you can tag a multi-arch image with some sort of version number that will correspond to the version we show in Umbrel. For example `ghcr.io/getalby/nostr-wallet-connect:v0.0.1`. 
Then in the `docker-compose.yml`, reference that image with the sha256 digest that corresponds to the mutli-arch image, not just the digest for one specific architecture like arm64. This will mean that you only need one version of your app and a user's Umbrel will automatically download the correct image for arm or x86 depending on what device their Umbrel is running on. 
For example, the `main-1d1c41c` image that you are currently using has the following multi-arch digest:
`sha256:bc2525f7a32fa2e032edb2ee5e7b931406dedd0ae6cf5874ef917bfd42d20428`. So your current setup could acutally just have one app that references `ghcr.io/getalby/nostr-wallet-connect:main-1d1c41c@sha256:bc2525f7a32fa2e032edb2ee5e7b931406dedd0ae6cf5874ef917bfd42d20428`.
 
2) **3-5 Gallery Images and App Icon**
You can make these yourselves or we can help! See here for example: https://apps.umbrel.com/app/nostr-relay
If you would like us to help, you can provide us with your logo, screenshots of the app interface that you want to showcase, and text that you'd like to show on each image and we can iterate back and forth.
For apps in the official Umbrel app store, the icon and gallery images are committed to [this repo](https://github.com/getumbrel/umbrel-apps-gallery) and are referenced generically in your apps `umbrel-app.yml` like this: https://github.com/getumbrel/umbrel-apps/blob/master/nostr-relay/umbrel-app.yml 


3) **Open a PR**
Open a PR named `App Submission: Alby Nostr Wallet Connect` to [this repo](https://github.com/getumbrel/umbrel-apps). The new directory for your app can be called something like `alby-nwc`.
Once you open the PR, I can help with additional review and testing of the app on Umbrel.

Let me know if I can help out with anything else prior to the PR.

**Comment by nmfretz** [comment]
Thanks for these @stackingsaunter! 

@MoritzKa. How are things looking for opening a PR to our apps repo? Is there anything in [this list](https://github.com/getAlby/umbrel-community-app-store/issues/1#issuecomment-1551936894) that you need help with?

**Comment by kiwiidb** [comment]
Hey @nmfretz , sorry for the late reply. We would almost be ready to publish the app, I'm looking at somewhere next week. I think we have everything we need, just been rather busy 👍

**Comment by kiwiidb** [comment]
@nmfretz I've opened a [PR](https://github.com/getumbrel/umbrel-apps/pull/636)
